/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cocktail;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author bahar
 */
public class CocktailGUI extends javax.swing.JFrame {
ArrayList<Ingredient>addedIngredients=new ArrayList();
      

    
    /**
     * Creates new form CocktailGUI
     */
    public CocktailGUI() {
        
        initComponents();
        this.blenderCapacity = Double.parseDouble(bsize.getText());
        this.cupCapacity = Double.parseDouble(csize.getText());
        this.filelogger=new FileLogger("log.log");
        this.blender = new Blender(blenderCapacity,filelogger);
        this.cup=new Cup(cupCapacity);
        pour.setEnabled(false);
        blend.setEnabled(false);
        
        
    }
     Logger filelogger;
     Cup cup ;
     double blenderCapacity;
     double cupCapacity;
     Blender blender;
     Ingredient ingredient ;
     RGBColor red = new RGBColor(255, 0, 0);
     RGBColor green = new RGBColor(0, 255, 0);
     RGBColor yellow = new RGBColor(0, 0, 255);
     RGBColor white = new RGBColor(255, 255, 255);
    
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
      void display (){
        String ListData[]=new String[addedIngredients.size()];
        for (int i = 0; i < addedIngredients.size(); i++) {
            Ingredient ing=addedIngredients.get(i);
            ListData[i]=ing.getName();
            
        }
        sings.setListData(ListData);
    
}
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ings = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        sings = new javax.swing.JList<>();
        select = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bsize = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        csize = new javax.swing.JTextField();
        blend = new javax.swing.JButton();
        pour = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(65, 105, 225));
        jLabel1.setText("Welcome ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 0, 147, -1));

        jLabel2.setFont(new java.awt.Font("Blackadder ITC", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(65, 105, 225));
        jLabel2.setText("select your ingrediants ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 127, 314, -1));

        ings.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrediants\n"));
        ings.setForeground(new java.awt.Color(51, 255, 0));
        ings.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Apple (60 cal , 15 ml)", "Banana (80 cal , 20ml)", "Orange ( 40 cal , 40ml)", "Milk (200 cal , 200 ml)", "Sugar (300  cal , One Cup)" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ings.setSelectionBackground(new java.awt.Color(255, 255, 255));
        ings.setSelectionForeground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(ings);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 178, 209, 148));

        sings.setBorder(javax.swing.BorderFactory.createTitledBorder("Selected Ingrediants\n"));
        sings.setForeground(new java.awt.Color(204, 204, 204));
        sings.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(sings);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 178, 200, 148));

        select.setForeground(new java.awt.Color(0, 128, 0));
        select.setText("Select");
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });
        getContentPane().add(select, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        jLabel3.setForeground(new java.awt.Color(54, 69, 79));
        jLabel3.setText("Blender's Size");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 77, -1, 22));

        bsize.setText("1000");
        bsize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsizeActionPerformed(evt);
            }
        });
        getContentPane().add(bsize, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 77, 71, -1));

        jLabel4.setForeground(new java.awt.Color(54, 69, 79));
        jLabel4.setText("Cup's Size");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 80, -1, -1));

        csize.setText("200");
        csize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csizeActionPerformed(evt);
            }
        });
        getContentPane().add(csize, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 77, 71, -1));

        blend.setForeground(new java.awt.Color(0, 128, 0));
        blend.setText("Blend");
        blend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blendActionPerformed(evt);
            }
        });
        getContentPane().add(blend, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 358, -1, -1));

        pour.setForeground(new java.awt.Color(0, 0, 255));
        pour.setText("Pour");
        pour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pourActionPerformed(evt);
            }
        });
        getContentPane().add(pour, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 358, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\bahar\\Desktop\\cok2.jpg")); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
     
        int index=ings.getSelectedIndex();
        if (index!=-1) {
            if(index == 4){
                // create sugar ingredient
                ingredient = new Sugar("Sugar",300);
                 try {
                      blender.addIngredient(ingredient);
                      addedIngredients.add(ingredient);
                    } catch (BlenderOverFlowException ex) {
                       ex.getMessage();
                    } 
                 display();
            } 
            else if(index == 3 ){
               ingredient = new Milk("milk",200,200 , white);
                     try {
                        blender.addIngredient(ingredient);
                        addedIngredients.add(ingredient);
                    } catch (BlenderOverFlowException ex) {
                       ex.getMessage();
                    }     
                     display();
            }
            else if(index == 2 ){
               ingredient = new Fruit("orange",40,40 ,new RGBColor(255, 255, 255));
                     try {
                        blender.addIngredient(ingredient);
                        addedIngredients.add(ingredient);
                    } catch (BlenderOverFlowException ex) {
                       ex.getMessage();
                    }     
                     display();
            }
             else if(index == 1 ){
               ingredient = new Fruit("Banana",80,20 ,yellow);
                     try {
                        blender.addIngredient(ingredient);
                        addedIngredients.add(ingredient);
                    } catch (BlenderOverFlowException ex) {
                       ex.getMessage();
                    }     
                     display();
            }
             else if(index == 0 ){
               ingredient = new Fruit("Apple",60,15 ,green);
                     try {
                        blender.addIngredient(ingredient);
                        addedIngredients.add(ingredient);
                    } catch (BlenderOverFlowException ex) {
                       ex.getMessage();
                    }     
                     display();
            }
               if (!addedIngredients.isEmpty()) {
            blend.setEnabled(true);
        }
         
        }else{
            JOptionPane.showMessageDialog(this, "Please select an ingredient to add");
        }
    }//GEN-LAST:event_selectActionPerformed

    private void pourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pourActionPerformed
           try {
            blender.pour(cup);
            
        }
           catch (CupsOverFlowException | EmptyBlenderException ex) {
            System.out.println(ex.getMessage());
        }
            JOptionPane.showMessageDialog(this, cup.getInfo());
    }//GEN-LAST:event_pourActionPerformed

    private void blendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blendActionPerformed

blender.blend();
JOptionPane.showMessageDialog(this, blender.getInfo());
pour.setEnabled(true);
    }//GEN-LAST:event_blendActionPerformed

    private void bsizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsizeActionPerformed
        blender.setCapacity(Double.parseDouble(bsize.getText()));
        System.out.println("blender"+blender.getCapacity());
    }//GEN-LAST:event_bsizeActionPerformed

    private void csizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csizeActionPerformed
     cup.setCapacity(Double.parseDouble(csize.getText()));

    }//GEN-LAST:event_csizeActionPerformed

    /**
     * @param args the command line arguments
     */
   // public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blend;
    private javax.swing.JTextField bsize;
    private javax.swing.JTextField csize;
    private javax.swing.JList<String> ings;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton pour;
    private javax.swing.JButton select;
    private javax.swing.JList<String> sings;
    // End of variables declaration//GEN-END:variables
}
